quarkus.rest-client.massive-api.url=https://api.massive.com/v3
quarkus.rest-client.massive-api.headers.Authorization=Bearer ${MASSIVE_API_KEY}
quarkus.rest-client.massive-api.headers.Host=api.massive.com
quarkus.rest-client.massive-api.jackson.serialize-inclusion=non-null
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=10000
logging.level.org.jboss.resteasy.reactive.client.logging=DEBUG